//department Action
export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST"
export const ADD_DEPARTMENT = "ADD_DEPARTMENT"


//role Action
export const GET_ROLE_LIST = "GET_ROLE_LIST"
export const ADD_ROLE  = "ADD_ROLE"   

//employee Action
export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST"
export const EDIT_ROLE_DATA = "EDIT_ROLE_DATA"
export const GET_PAGINATED_DATA_EMPLOYEE = "GET_PAGINATED_DATA_EMPLOYEE"
export const GET_FIRST_PAGE_EMPLOYEE = "GET_FIRST_PAGE_EMPLOYEE"